server:
  port: 8081
#-----------------------------------数据源---------------------------------------
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    data-username: root
    data-password: 1234
#-----------------------------------log-----------------------------------------
logging:
  config: classpath:logback-debug.xml
